FROM nvidia/cuda:12.0.0-devel-ubuntu22.04
WORKDIR /usr/src/app
RUN apt update && apt -y install python3.10 python3-pip
COPY ./requirements.txt ./
RUN pip3 install torch
RUN pip3 install --no-cache-dir -r requirements.txt
RUN apt update && apt install -y git
RUN FLASH_ATTENTION_SKIP_CUDA_BUILD=TRUE pip3 install flash-attn --no-build-isolation